server:
  port: 9001
  servlet:
    context-path: /hzh-user
spring:
  datasource:
    url: jdbc:mysql://192.168.65.131:3306/hzh_tsfse?useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 5q6W7e8R
    driver-class-name: com.mysql.jdbc.Driver
  shardingsphere:
    sharding:
      default-database-strategy:
      tables:
#      discovery:
#        cluster-name: HZ

  # 邮件发送
  mail:
    host: smtp.qq.com
    port: 465
    username: 1391210212@qq.com
    password: Asdfghjkl629...
    default-encoding: UTF-8
    protocol: smtps


  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为loaclhost）
    host: 192.168.65.131
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    #password: pwd123
    # redis连接超时时间（单位毫秒）
    #timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      #最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

mybatis-plus:
  type-aliases-package: com.hzh.common.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#  global-config:
#    db-config:
#      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值（默认为1）
#      logic-not-delete-value: 0  # 逻辑未删除值（默认为0）
  mapper-locations: classpath*:com/hzh/common/mapper/xml/*.xml
  #不管用
  #mapper-locations:
  #  - classpath*:**/mapper/xml/*.xml

#  微服务A 调用 B， 即：A是客户端，B是服务端。 这个是客户端配置，因此要配在A里面。
#  其中“default” 是全局配置，对所有的 @FeignClient 生效，
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss
  file:
    name: ${user.home}/logs/user/hzh-user.log
    max-size: 100MB
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka

#配置种有共有属性----优先级  服务名-profile.yaml  >  服务名.yaml  >  本地配置
# 优先级即                当前环境配置          >  共享环境配置   >  本地配置
pattern:
  name: 本地环境local