server:
  port: 8001
  servlet:
    context-path: /hzh-team

spring:
  datasource:
    url: jdbc:mysql://192.168.65.131:3306/hzh_tsfse?useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 5q6W7e8R
  application:
    name: teamService
  cloud:
    nacos:
      server-addr: 192.168.65.131:8848    # nacos服务地址
      discovery:
        namespace: 14be9d75-e2d3-4d73-9db1-65ef410240b4 # dev环境
        ephemeral: false # 是否是临时实例

  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为loaclhost）
    host: 192.168.65.131
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    #password: pwd123
    # redis连接超时时间（单位毫秒）
    #timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      #最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#是否激活 swagger true or false
swagger:
  enable: true

#对feign的优化 一个是 引入httpclient 开启连接池  另一个是日志开启级别
feign:
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数

